/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package calculadoratrig;

/**
 *
 * @author estudiantes
 */
public class CalculadoraGrafica extends javax.swing.JFrame {
    Calculador miCalculador=new Calculador();
    /**
     * Creates new form CalculadoraGrafica
     */
    public CalculadoraGrafica() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Result = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        Numero1 = new javax.swing.JTextField();
        Numero2 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        ButtonSuma = new javax.swing.JButton();
        ButtonResta = new javax.swing.JButton();
        ButtonMult = new javax.swing.JButton();
        ButtonDiv = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        Seno = new javax.swing.JButton();
        Coseno = new javax.swing.JButton();
        Tangente = new javax.swing.JButton();
        Secante = new javax.swing.JButton();
        Cosecante = new javax.swing.JButton();
        Cotangente = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Número 1");

        jLabel2.setText("Número 2");

        ButtonSuma.setText("+");
        ButtonSuma.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ButtonSumaMouseClicked(evt);
            }
        });

        ButtonResta.setText("-");
        ButtonResta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ButtonRestaMouseClicked(evt);
            }
        });

        ButtonMult.setText("*");
        ButtonMult.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ButtonMultMouseClicked(evt);
            }
        });

        ButtonDiv.setText("/");
        ButtonDiv.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ButtonDivMouseClicked(evt);
            }
        });

        jLabel3.setText("Resultado");

        Seno.setText("Sen");
        Seno.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SenoMouseClicked(evt);
            }
        });

        Coseno.setText("Cos");
        Coseno.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CosenoMouseClicked(evt);
            }
        });

        Tangente.setText("Tan");
        Tangente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TangenteMouseClicked(evt);
            }
        });

        Secante.setText("Sec");
        Secante.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SecanteMouseClicked(evt);
            }
        });

        Cosecante.setText("Cosc");
        Cosecante.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CosecanteMouseClicked(evt);
            }
        });

        Cotangente.setText("Cot");
        Cotangente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CotangenteMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(ButtonSuma, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(186, 186, 186)
                        .addComponent(jLabel3))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(94, 94, 94)
                        .addComponent(Result, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(Seno)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel2)
                                .addComponent(jLabel1)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Numero2, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Numero1, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(5, 5, 5)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(ButtonResta, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(49, 49, 49)
                                        .addComponent(ButtonMult, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(47, 47, 47)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(Secante)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(Cosecante))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(Coseno)
                                                .addGap(58, 58, 58)
                                                .addComponent(Tangente)))))
                                .addGap(56, 56, 56)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(ButtonDiv, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Cotangente))))))
                .addGap(55, 70, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Numero1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(Numero2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ButtonSuma)
                    .addComponent(ButtonResta)
                    .addComponent(ButtonMult)
                    .addComponent(ButtonDiv))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Coseno)
                            .addComponent(Tangente)
                            .addComponent(Seno)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(Cotangente)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Cosecante)
                    .addComponent(Secante))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Result, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addGap(7, 7, 7))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ButtonSumaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ButtonSumaMouseClicked
        // TODO add your handling code here:
        miCalculador.Operacion="+";
        miCalculador.Num1= Double.parseDouble(Numero1.getText());
        miCalculador.Num2= Double.parseDouble(Numero2.getText());
        Result.setText(Double.toString(miCalculador.CalcularOperacion()));
 
    }//GEN-LAST:event_ButtonSumaMouseClicked

    private void ButtonRestaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ButtonRestaMouseClicked
        // TODO add your handling code here:
        miCalculador.Operacion="-";
        miCalculador.Num1= Double.parseDouble(Numero1.getText());
        miCalculador.Num2= Double.parseDouble(Numero2.getText());
        Result.setText(Double.toString(miCalculador.CalcularOperacion()));
    }//GEN-LAST:event_ButtonRestaMouseClicked

    private void ButtonMultMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ButtonMultMouseClicked
        // TODO add your handling code here:
       miCalculador.Operacion="*";
        miCalculador.Num1= Double.parseDouble(Numero1.getText());
        miCalculador.Num2= Double.parseDouble(Numero2.getText());
        Result.setText(Double.toString(miCalculador.CalcularOperacion()));
    }//GEN-LAST:event_ButtonMultMouseClicked

    private void ButtonDivMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ButtonDivMouseClicked
        // TODO add your handling code here:
        miCalculador.Operacion="/";
        miCalculador.Num1= Double.parseDouble(Numero1.getText());
        miCalculador.Num2= Double.parseDouble(Numero2.getText());
        Result.setText(Double.toString(miCalculador.CalcularOperacion()));
    }//GEN-LAST:event_ButtonDivMouseClicked

    private void SenoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SenoMouseClicked
        miCalculador.Operacion="Sen";
        miCalculador.Num1= Double.parseDouble(Numero1.getText());
        Result.setText(Double.toString(miCalculador.CalcularOperacion()));
// TODO add your handling code here:
    }//GEN-LAST:event_SenoMouseClicked

    private void CosenoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CosenoMouseClicked

        miCalculador.Operacion="Cos";
        miCalculador.Num1= Double.parseDouble(Numero1.getText());
        Result.setText(Double.toString(miCalculador.CalcularOperacion()));        // TODO add your handling code here:
    }//GEN-LAST:event_CosenoMouseClicked

    private void TangenteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TangenteMouseClicked
        miCalculador.Operacion="Tan";
        miCalculador.Num1= Double.parseDouble(Numero1.getText());
        Result.setText(Double.toString(miCalculador.CalcularOperacion()));
        // TODO add your handling code here:
    }//GEN-LAST:event_TangenteMouseClicked

    private void CotangenteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CotangenteMouseClicked
        miCalculador.Operacion="Cot";
        miCalculador.Num1= Double.parseDouble(Numero1.getText());
        Result.setText(Double.toString(miCalculador.CalcularOperacion()));
        // TODO add your handling code here:
    }//GEN-LAST:event_CotangenteMouseClicked

    private void SecanteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SecanteMouseClicked
        miCalculador.Operacion="Sec";
        miCalculador.Num1= Double.parseDouble(Numero1.getText());
        Result.setText(Double.toString(miCalculador.CalcularOperacion()));
        // TODO add your handling code here:
    }//GEN-LAST:event_SecanteMouseClicked

    private void CosecanteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CosecanteMouseClicked
        miCalculador.Operacion="Cosc";
        miCalculador.Num1= Double.parseDouble(Numero1.getText());
        Result.setText(Double.toString(miCalculador.CalcularOperacion()));
        // TODO add your handling code here:
    }//GEN-LAST:event_CosecanteMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CalculadoraGrafica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CalculadoraGrafica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CalculadoraGrafica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CalculadoraGrafica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CalculadoraGrafica().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonDiv;
    private javax.swing.JButton ButtonMult;
    private javax.swing.JButton ButtonResta;
    private javax.swing.JButton ButtonSuma;
    private javax.swing.JButton Cosecante;
    private javax.swing.JButton Coseno;
    private javax.swing.JButton Cotangente;
    private javax.swing.JTextField Numero1;
    private javax.swing.JTextField Numero2;
    private javax.swing.JTextField Result;
    private javax.swing.JButton Secante;
    private javax.swing.JButton Seno;
    private javax.swing.JButton Tangente;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
